import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Layout from "@/app/layout/components/layout";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v13-appRouter";
import React from "react";
import StoreProvider from "@/app/providers/store-provider";
import { AuthInitializer } from "@/app/core/Initializer/AuthInitializer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      dir="rtl"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="h-full flex flex-col !bg-[#F6F6F6]">
        <AppRouterCacheProvider>
          <StoreProvider>
            <AuthInitializer>
              <Layout>{children}</Layout>
            </AuthInitializer>
          </StoreProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
